# Generated by Django 3.1.3 on 2020-11-05 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_name', models.CharField(default='new playlist', max_length=50)),
                ('created_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(default='profilepic/default.png', null=True, upload_to='profilepic/')),
                ('cover_pic', models.ImageField(default='coverpic/default.jpg', null=True, upload_to='coverpic/')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.CharField(max_length=50)),
                ('video_description', models.TextField()),
                ('published_date', models.DateField(auto_now=True)),
                ('video_file', models.FileField(null=True, upload_to='videos/')),
                ('thumbnail', models.ImageField(null=True, upload_to='thumbnails/')),
                ('video_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='liked_videos',
            field=models.ManyToManyField(related_name='user_liked_videos', to='core.Video'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='saved_playlists',
            field=models.ManyToManyField(to='core.Playlist'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='viewed_videos',
            field=models.ManyToManyField(related_name='user_viewed_videos', to='core.Video'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='playlist_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.userprofile'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='playlist_videos',
            field=models.ManyToManyField(null=True, to='core.Video'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField(max_length=300)),
                ('comment_datetime', models.DateTimeField()),
                ('comment_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.userprofile')),
                ('commented_video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.video')),
            ],
        ),
    ]
