# Generated by Django 3.1.3 on 2020-11-05 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='cover_pic',
            field=models.ImageField(blank=True, default='coverpic/default.jpg', null=True, upload_to='coverpic/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='liked_videos',
            field=models.ManyToManyField(blank=True, related_name='user_liked_videos', to='core.Video'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profilepic/default.png', null=True, upload_to='profilepic/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='saved_playlists',
            field=models.ManyToManyField(blank=True, to='core.Playlist'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='viewed_videos',
            field=models.ManyToManyField(blank=True, related_name='user_viewed_videos', to='core.Video'),
        ),
    ]
